[phases.setup]
nixPkgs = ['python310']

[phases.install]
cmds = ['python3 -m pip install -r requirements.txt']

[phases.build]
cmds = []

[start]
cmd = 'cd backend && python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT'
